#!/bin/bash
if [[ ${#} -eq 1 && ("${1}" == "-help" || "${1}" == "-h") ]]
then
  echo "Format files by finding and replacing patterns in filename"
  echo "Usage: ${0} [<find>] [<replace>]"
  echo "  - <find> : Pattern to find in the file name"
  echo "  - <replace> : Pattern to replace in the file name"
  exit 0
fi

find=""
repl=""
if [ ${#} -eq 1 ]
then
  find=${1}
elif [ ${#} -eq 2 ]
then
  find=${1}
  repl=${2}
fi

# Iterate through all files in current dir
IFS=$'\n'
for file in `ls -1`
do
  new_file=$file 
  if [ ! -z $find ]
  then
    new_file=`echo $new_file | sed -e "s%$find%$repl%g"`
  fi
  new_file=`echo $new_file | tr -d \'\"\, | sed "s% %_%g"` 
  if [ ! -e $new_file ]
  then
    echo "Rename '$file' as '$new_file'"
    mv "$file" "$new_file"
  fi
done
