#!/bin/bash
if [[ $# -eq 0 ]]
then
   echo "Usage: ${0} [ <dir> ] <pattern to find>"
   exit 0
fi

if [[ $# -eq 1 ]]
then
   dir="."
   pattern=${1}
elif [[ $# -eq 2 ]]
then
   dir=${1}
   pattern=${2}
fi

find $dir -name "$pattern" 
